#!/bin/sh
case "$1" in
  post)
    (
      sleep 2
      /usr/bin/systemctl restart iio-sensor-proxy.service
      /usr/bin/systemctl restart hexagonrpcd-sdsp.service
      /usr/bin/systemctl restart iio-sensor-proxy.service
    ) >/dev/null 2>&1 &
  ;;
esac
